language: node_js
node_js:
  - 8
  - 10
  - 12

before_script:
  - npm pack
  - npm i -g $(find . -name 'npr-*') # install the package globally

jobs:
  include:
    node_js: node
    # the next are truly E2E tests
    script: npr test
    script: npr unit:test -t 'Trap succeed'
    script: npr unit:test -- -t 'Trap succeed'

after_success: npm run semantic-release
